const words = [
    { word: "addition", hint: "Process of adding numbers" },
    { word: "meeting", hint: "Event where people come together" },
    { word: "number", hint: "Math symbol for counting" },
    { word: "exchange", hint: "Act of trading" },
    { word: "canvas", hint: "Fabric for oil painting" },
    { word: "garden", hint: "Space for planting flowers and plants" },
    { word: "position", hint: "Location of someone or something" },
    { word: "feather", hint: "Bird's outer covering" },
    { word: "comfort", hint: "Pleasant feeling of relaxation" },
    { word: "tongue", hint: "Muscular organ in the mouth" },
    { word: "expansion", hint: "Process of increasing or growing" },
    { word: "country", hint: "Politically identified region" },
    { word: "group", hint: "Collection of objects or persons" },
    { word: "taste", hint: "Ability to detect flavors" },
    { word: "store", hint: "Large shop for trading goods" },
    { word: "field", hint: "Land area for farming activities" },
    { word: "friend", hint: "Person outside of family" },
    { word: "pocket", hint: "Bag for carrying small items" },
    { word: "needle", hint: "Thin, sharp metal pin" },
    { word: "expert", hint: "Person with extensive knowledge" },
    { word: "statement", hint: "Declaration of something" },
    { word: "second", hint: "Unit of time" },
    { word: "library", hint: "Place with book collection" },
];
